apiVersion: v1
kind: Pod
metadata:
 name: secret-volume-pod 
spec:
 containers:
  - name: application-vol
    image: busybox
    command:
     - sh
     - -c
     - sleep 3600
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/credentials
        readOnly: true
 volumes:
  - name: secret-volume
    secret:
     secretName: db-credentials 
