apiVersion: v1
kind: Pod
metadata:
 name: secret-envfrom-pod
spec:
 containers:
  - name: application
    image: busybox
    command:
     - sh
     - -c
     - sleep 3600
    envFrom:
     - secretRef: 
        name: db-credentials
