apiVersion: v1
kind: Pod
metadata:
 name: oom-pod
spec:
 containers:
  - name: app
    image: python:3.12-alpine
    resources:
     requests:
      memory: "64Mi"
     limits:
      memory: "128Mi"
    command:
     - python
     - -c
     - |
       data = bytearray(200 * 1024 * 1024)
       print("Allocated Memory chunks")
       import time
       time.sleep(3600)
