apiVersion: v1
kind: Pod
metadata:
 name: resource-pod
spec:
 containers:
  - name: app-pod
    image: nginx:alpine
    resources:
     requests:
      cpu: "500m"
      memory: "256Mi"
     limits:
      cpu: "1"
      memory: "512Mi"
