apiVersion: v1
kind: Pod
metadata:
 name: configmap-env-pod
spec:
 containers:
   - name: appplication-container
     image: busybox
     command:
      - sh
      - -c
      - sleep 3600
     env:
      - name: APP_ENV
        valueFrom:
         configMapKeyRef:
          name: app-config
          key: APP_ENV

      - name: APP_NAME
        valueFrom:
         configMapKeyRef:
          name: app-config
          key: APP_NAME
